export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const CLEAR_MOVIE = "CLEAR_MOVIE";
export const FETCH_MOVIE_REVIEWS = "FETCH_MOVIE_REVIEWS";
export const FETCH_MOVIE_TRAILERS = "FETCH_MOVIE_TRAILERS";